name: Build and deploy

on: push

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --pure-lockfile --prefer-offline

      - name: Build packages
        run: yarn build

      - name: Build storybook
        run: yarn build:storybook

      - name: Deploy docs when tag
        if: startsWith(github.ref, 'refs/tags/@tecsinapse/react-*@*')
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: sbdocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
