name: Release and deploy

on:
  push:
    tags:
      - '@tecsinapse/react-*@*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
        
      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --pure-lockfile --prefer-offline
        
      - name: Build storybook
        run: yarn build:storybook
        
      - name: Deploy docs
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: sbdocs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
